Repository PDXCapstoneF/SPECtate, pull requests merged in 2018-04, with the labels that each got.

#10 Completed docstrings for each function. Added file descripti…
  dialogue.py
Labels: Documentation

#12 Added a basic readme.
  README.md
Labels: Documentation

#14 Fix uninstall of pipenv causing travis builds to fail
  .travis.yml
Labels: bug

#29 Add docopt
  .travis.yml
  Pipfile
  Pipfile.lock
Labels: bug

#27 Blackbox Unit Tests
  mainCLI.py
  tests/test_mainCLI.py
Labels: enhancement

#28 Customize Run Context, Optional Run Cleanup
  mainCLI.py
Labels: enhancement

#30 Add Configuration validation using `schema` library
  Pipfile
  Pipfile.lock
  mainCLI.py
  src/__init__.py
  src/validate.py
  tests/fixtures/sample_config_invalid.json
  tests/test_validate.py
Labels: Documentation, enhancement
