Repository PDXCapstoneF/SPECtate, pull requests merged in 2018-05, with the labels that each got.

#81 Add pip cache per https://docs.travis-ci.com/user/caching/#pip-cache
  .travis.yml
Labels: enhancement

#90 Add sample for Github Pages and ReadTheDocs
  docs/Conversation-on-Props.md
  docs/Conversation-on-Run-Templates.md
  docs/Home.md
  docs/INDEX.md
  docs/Tate-Config.md
  docs/Working-in-Virtual-Environments.md
Labels: Documentation

#132 Replace default_props with prop_options in source
  src/run_generator.py
  src/validate.py
  tests/test_validate.py
Labels: bug

#123 (GUI) User can create runs
  gui/mainGUI.py
  gui/run_manager.py
Labels: gui

#150 Fix results directory not being used
  src/benchmark_run.py
Labels: bug

#143 Rename to use readthedocs.io convention for index
  docs/index.md
Labels: Documentation

#136 Add more documentation to the SPECtate core
  src/benchmark_run.py
  src/run_generator.py
  src/validate.py
  tests/test_validate.py
Labels: Documentation

#161 Fix additional directories created when running tests
  tests/test_benchmark_run.py
Labels: bug

#162 Add option for dry run in SpecJBBRun
  mainCLI.py
  src/benchmark_run.py
Labels: enhancement

#149 Set working directory for runs
  68c5021657bc484bafdb70cb5bc3db74/specjbb2015.props
  cd3405055e524b47942bcd5f2da5f6c2/specjbb2015.props
  d232e5d507f34acdb57c3dec3f92a534/specjbb2015.props
  src/benchmark_run.py
  src/run_generator.py
  src/validate.py
Labels: enhancement

#180 Remove additional props accidentally committed to the tree
  68c5021657bc484bafdb70cb5bc3db74/specjbb2015.props
  cd3405055e524b47942bcd5f2da5f6c2/specjbb2015.props
  d232e5d507f34acdb57c3dec3f92a534/specjbb2015.props
Labels: bug

#172 Do (limited) compliant run validation
  mainCLI.py
  src/benchmark_run.py
  src/compliant.py
  tests/test_benchmark_run.py
  tests/test_compliant.py
Labels: enhancement

#181 path fix in GUI
  gui/run_manager.py
Labels: gui

#187 Update documentation for SPECtate in docs/
  README.md
  docs/index.md
Labels: Documentation
